background            #191B1B

color0                #191B1B
color1                #7B9C2F
color2                #6EE2A9
color3                #A2F9AB
color4                #75B5B7
color5                #83ACEC
color6                #85D9C3
color7                #D0DBCD
color8                #B4BCAF
color9                #A1D043
color10               #F6FFF7
color11               #FFFFFF
color12               #BEE4DE
color13               #CADBFF
color14               #E8FFF5
color15               #DDE3E5

cursor                #D0DBCD

foreground            #D0DBCD

selection_background  #DAE4E4
selection_foreground  #3F4949

# Override obscure colors for starship prompt (these are greys at the end)
color255              #B8CACA
color254              #394A4A
color253              #BEC8C8
color252              #3F4949
color251              #B0CCCC
color250              #7B9696
color249              #FFB4AB
color248              #93000A

color232              #233334
color233              #D3E6E6
color234              #293232
color235              #DAE4E4
color236              #1B3435
color237              #000000
color238              #690005
color239              #FFDAD6
color240              #233334
# Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #B8CACA
color244              #FFB4AB
color245              #464747
